export const lightColors = {
    primary: "text-green-600",
    primaryBg: "bg-green-500",
    primaryBgLight: "bg-green-50/50",
    secondary: "text-slate-700",
    secondaryBg: "bg-slate-100",
    background: "bg-slate-50",
    border: "border-green-300",
    text: "text-slate-900",
    muted: "text-slate-600",
    accent: "text-green-600",
    cardBg: "bg-white border border-green-200",
    cardBorder: "border-green-300",
    iconBg: "bg-green-100 text-green-700 border border-green-300",
    button: "bg-green-600 hover:bg-green-700 text-white border border-green-500",
    gradientBorder: "from-green-500 to-emerald-500",
    timelineLine: "#cbd5e1",
    schoolIcon: "#059669",
    workIcon: "#16a34a",
    socialIcon: "text-slate-600 hover:text-green-600 transition-colors",
    highlight: "bg-green-500",
    glow: "shadow-lg shadow-green-500/20",
    prompt: "text-green-600",
    command: "text-blue-600",
    output: "text-slate-700",
    error: "text-red-600",
};

export const darkColors = {
    primary: "text-green-400",
    primaryBg: "bg-green-500/20",
    primaryBgLight: "bg-green-900/20",
    secondary: "text-slate-300",
    secondaryBg: "bg-slate-950",
    background: "bg-slate-950",
    border: "border-slate-800",
    text: "text-slate-100",
    muted: "text-slate-400",
    accent: "text-green-400",
    cardBg: "bg-slate-900 border border-slate-800",
    cardBorder: "border-slate-800",
    iconBg: "bg-slate-800 text-slate-200 border border-slate-700",
    button: "bg-green-500 hover:bg-green-600 text-white border border-green-400",
    gradientBorder: "from-green-400 to-emerald-400",
    timelineLine: "#284a2f",
    schoolIcon: "#10b981",
    workIcon: "#22c55e",
    socialIcon: "text-slate-300 hover:text-green-400 transition-colors",
    highlight: "bg-green-500",
    glow: "shadow-lg shadow-green-500/30",
    prompt: "text-green-400",
    command: "text-blue-400",
    output: "text-slate-100",
    error: "text-red-400",
};

export const getThemeColors = (theme) =>
    theme === "light" ? lightColors : darkColors;
